[package]
name = "ilias_uploader_utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest ={version =  "0.11.17", features = ["cookies", "multipart", "blocking"]}
scraper = "0.16.0"
clap = { version = "4.2.7", features = ["derive"] }
dialoguer = "0.10.4"
keyring = "2.0.2"
toml = "0.7.3"
serde = "1.0.163"
