[package]
name = "ilias_uploader_utility"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest ={version =  "0.11.17", features = ["cookies", "multipart", "blocking"]}
scraper = "0.16.0"
tokio = { version = "1.28.0", features = ["full"] }
futures = "0.3.28"
# https://crates.io/crates/scraper
# https://crates.io/crates/voyager
# https://crates.io/crates/reqwest