[package]
name = "ilias_uploader_utility"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest ={version =  "0.11.22", features = ["cookies", "multipart", "blocking"]}
scraper = "0.17.1"
clap = { version = "4.4.6", features = ["derive"] }
dialoguer = "0.11.0"
keyring = "2.0.5"
toml = "0.8.2"
serde = { version = "1.0.189", features = ["derive"] }
regex = "1.10.2"
anyhow = "1.0.75"
